mvcProyectoWeb1/Areas/Admin/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using mvcProyectoWeb1.AccesoDatos.Data.Repository.IRepository;
using mvcProyectoWeb1.Models;

namespace mvcProyectoWeb1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriaController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        public CategoriaController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                //logica para guardar en bd
                _contenedorTrabajo.Categoria.Add(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));

            }
            return View(categoria);
        }
        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Categoria categoria = new Categoria();
            categoria = _contenedorTrabajo.Categoria.Get(id);
            if (categoria == null)
            {
                return NotFound();

            }
            return View(categoria);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Categoria categoria)
        {

            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Categoria.Update(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }
        #region llamadas a la api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Categoria.GetAll() });
        }
        [Authorize(Roles = "admin")]
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _contenedorTrabajo.Categoria.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error borrando categoria" });
            }
            _contenedorTrabajo.Categoria.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Se borro la cateegoria" });
        }
        #endregion

    }
}

mvcProyectoWeb1/Areas/Admin/Controllers/CompraController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using mvcProyectoWeb1.AccesoDatos.Data.Repository.IRepository;
using mvcProyectoWeb1.Models;

namespace mvcProyectoWeb1.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class CompraController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public CompraController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Producto = new SelectList(_contenedorTrabajo.Producto.GetAll(), "Id", "Nombre");
            ViewBag.Proveedor = new SelectList(_contenedorTrabajo.Proveedor.GetAll(), "Id", "Nombre");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Compra compra)
        {
            if (ModelState.IsValid)
            {
                //logica para guardar en bd
                _contenedorTrabajo.Compra.Add(compra);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));

            }
            ViewBag.Producto = new SelectList(_contenedorTrabajo.Producto.GetAll(), "Id", "Nombre");
            ViewBag.Proveedor = new SelectList(_contenedorTrabajo.Proveedor.GetAll(), "Id", "Nombre");
            return View(compra);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Compra compra = new Compra();
            compra = _contenedorTrabajo.Compra.Get(id);
            if (compra == null)
            {
                return NotFound();

            }
            ViewBag.Producto = new SelectList(_contenedorTrabajo.Producto.GetAll(), "Id", "Nombre");
            ViewBag.Proveedor = new SelectList(_contenedorTrabajo.Proveedor.GetAll(), "Id", "Nombre");
            return View(compra);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Compra compra)
        {

            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Compra.Update(compra);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Producto = new SelectList(_contenedorTrabajo.Producto.GetAll(), "Id", "Nombre");
            ViewBag.Proveedor = new SelectList(_contenedorTrabajo.Proveedor.GetAll(), "Id", "Nombre");
            return View(compra);
        }
        #region llamadas a la api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Compra.GetAll() });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _contenedorTrabajo.Compra.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error borrando Compra" });
            }
            _contenedorTrabajo.Compra.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Se borro la compra" });
        }
        #endregion
    }
}

mvcProyectoWeb1/Areas/Admin/Controllers/ProveedorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using mvcProyectoWeb1.AccesoDatos.Data.Repository.IRepository;
using mvcProyectoWeb1.Models;

namespace mvcProyectoWeb1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProveedorController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public ProveedorController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Proveedor proveedor)
        {
            if (ModelState.IsValid)
            {
                //logica para guardar en bd
                _contenedorTrabajo.Proveedor.Add(proveedor);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));

            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Proveedor proveedor = new Proveedor();
            proveedor = _contenedorTrabajo.Proveedor.Get(id);
            if (proveedor == null)
            {
                return NotFound();

            }
            return View(proveedor);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Proveedor proveedor)
        {

            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Proveedor.Update(proveedor);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(proveedor);
        }
        #region llamadas a la api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Proveedor.GetAll() });
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _contenedorTrabajo.Proveedor.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error borrando proveedor" });
            }
            _contenedorTrabajo.Proveedor.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Se borro la proveedor" });
        }
        #endregion
    }
}

mvcProyectoWeb1/Areas/Admin/Controllers/SlidersController.cs
using Microsoft.AspNetCore.Mvc;
using mvcProyectoWeb1.AccesoDatos.Data.Repository.IRepository;
using mvcProyectoWeb1.Models;

namespace mvcProyectoWeb1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SlidersController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public SlidersController(IContenedorTrabajo contenedorTrabajo,
            IWebHostEnvironment hostingEnvironment)
        {
            _contenedorTrabajo = contenedorTrabajo;
            _hostingEnvironment = hostingEnvironment;
        }
        [HttpGet]
        public IActionResult Index() { return View(); }
        [HttpGet]
        public IActionResult Create() { return View(); }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Slider slider)
        {
            if (ModelState.IsValid)
            {
                string rutaPrincipal = _hostingEnvironment.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;
                if (archivos.Count() > 0)
                {
                    //Nuevo slider
                    string nombreArchivo = Guid.NewGuid().ToString();
                    var subidas = Path.Combine(rutaPrincipal, @"imagenes\sliders");
                    var extension = Path.GetExtension(archivos[0].FileName);
                    using (var fileStreams = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                    {
                        archivos[0].CopyTo(fileStreams);
                    }
                    slider.UrlImagen = @"\imagenes\sliders\" + nombreArchivo + extension;
                    _contenedorTrabajo.Slider.Add(slider);
                    _contenedorTrabajo.Save();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Imagen", "Debes seleccionar una imagen");
                }

            }
            return View(slider);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                var slider = _contenedorTrabajo.Slider.Get(id.GetValueOrDefault());
                return View(slider);
            }

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Slider slider)
        {
            if (ModelState.IsValid)
            {
                string rutaPrincipal = _hostingEnvironment.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;

                var sliderDdesdeBd = _contenedorTrabajo.Slider.Get(slider.Id);

                if (archivos.Count() > 0)
                {
                    //Nuevo imagen slider
                    string nombreArchivo = Guid.NewGuid().ToString();
                    var subidas = Path.Combine(rutaPrincipal, @"imagenes\sliders");
                    var extension = Path.GetExtension(archivos[0].FileName);
                    //var nuevaExtension = Path.GetExtension(archivos[0].FileName);
                    var rutaImagen = Path.Combine(rutaPrincipal, sliderDdesdeBd.UrlImagen.TrimStart('\\'));
                    if (System.IO.File.Exists(rutaImagen))
                    {
                        System.IO.File.Delete(rutaImagen);
                    }
                    //Nuevamente subimos el archivo
                    using (var fileStreams = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                    {
                        archivos[0].CopyTo(fileStreams);
                    }
                    slider.UrlImagen = @"\imagenes\sliders\" + nombreArchivo + extension;
                    _contenedorTrabajo.Slider.Update(slider);
                    _contenedorTrabajo.Save();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    //Aquí sería cuando la imagen ya existe y se conserva
                    slider.UrlImagen = sliderDdesdeBd.UrlImagen;
                }
                _contenedorTrabajo.Slider.Update(slider);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(slider);
        }
        #region Llamadas a la API
        [HttpGet]
        public IActionResult GetAll()
        { return Json(new { data = _contenedorTrabajo.Slider.GetAll() }); }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var sliderDesdeBd = _contenedorTrabajo.Slider.Get(id);
            string rutaDirectorioPrincipal = _hostingEnvironment.WebRootPath;
            var rutaImagen = Path.Combine(rutaDirectorioPrincipal, sliderDesdeBd.UrlImagen.TrimStart('\\'));
            if (System.IO.File.Exists(rutaImagen))
            {
                System.IO.File.Delete(rutaImagen);
            }
            if (sliderDesdeBd == null)
            {
                return Json(new { success = false, message = "Error borrando slider" });
            }
            _contenedorTrabajo.Slider.Remove(sliderDesdeBd);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Slider Borrado Correctamente" });
        }
        #endregion
    }
}

mvcProyectoWeb1/Areas/Admin/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using mvcProyectoWeb1.AccesoDatos.Data.Repository.IRepository;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace mvcProyectoWeb1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UsuariosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        public UsuariosController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var usuarioActual = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(_contenedorTrabajo.Usuario.GetAll(u => u.Id != usuarioActual.Value));
        }
        [HttpGet]
        public IActionResult Bloquear(string id) 
        { 
            if (id == null)
            {
                return NotFound();
            }
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var usuarioActual=claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            _contenedorTrabajo.Usuario.BloquearUsuario(id);
            return View("Index",_contenedorTrabajo.Usuario.GetAll(u => u.Id != usuarioActual.Value));
        }
        [HttpGet]
        public IActionResult Desbloquear(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var usuarioActual = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            _contenedorTrabajo.Usuario.DesbloquearUsuario(id);
            return View("Index", _contenedorTrabajo.Usuario.GetAll(u => u.Id != usuarioActual.Value));
        }
    }
}

mvcProyectoWeb1/Views/Shared/_Layout.cshtml
@using mvcProyectoWeb1.Utilidades
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvcProyectoWeb1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap5.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Cliente" asp-controller="Home" asp-action="Index">
                                <img src="~/imagenes/Logotipo/computadora.png" alt="Logo" style="width: 60px; height: auto; margin-right: 10px;">
                                Inicio
                            </a>
                        </li>
                        @if (User.IsInRole(CNT.Administrador))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Ver Tablas</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Categoria" asp-action="Index">Categoria</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Producto" asp-action="Index">Producto</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Proveedor" asp-action="Index">Proveedor</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Transaccion" asp-action="Index">Transaccion</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Compra" asp-action="Index">Compra</a>
                                </div>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link dropdown" asp-area="Admin" asp-controller="Usuarios" asp-action="Index">Lista de Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link dropdown" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Sliders</a>
                        </li>
                        }
                        @if (User.IsInRole(CNT.Cliente))
                        {
                            <li class="nav-item">
                                <a class="nav-link dropdown" asp-area="Admin" asp-controller="Producto" asp-action="Index">Producto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link dropdown" asp-area="Admin" asp-controller="Categoria" asp-action="Index">Categoria</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link dropdown" asp-area="Admin" asp-controller="Contactos" asp-action="Index">Contactos</a>
                            </li>
                        }
                    </ul>
                    <form class="busqueda d-flex ms-3 mr-4" asp-controller="Home" asp-action="ResultadoBusqueda" method="get">
                        <input class="form-control text-dark" type="text" name="searchString" placeholder="Texto a buscar">
                        <div class="input-group-append">
                            <button class="btn btn-success" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
        <!--Aquí vista parcial slider-->
        @if (ViewBag.IsHome == true)
        {
            <partial name="_Slider" />
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - mvcProyectoWeb1
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--Js plugins-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mvcProyectoWeb1/Views/Shared/_Slider.cshtml
@model mvcProyectoWeb1.Models.ViewModels.HomeVM

<div id="sliderImagenes" class="carousel slide">
    <div class="carousel-inner">
        @{
            int cont = 0;
        }

        @foreach (var slider in Model.Sliders)
        {
            var itemDinamico = cont++ == 0 ? "active" : "";

            @if (slider.Estado == true)
            {
                <div class="carousel-item @itemDinamico">
                    <img src="@Url.Content(slider.UrlImagen)" class="d-block w-100" style="width:1px; height:370px">
                    @* <h1> Bienvenido a Computer</h1> *@
                    <h1 class="text-white text-center bg-dark py-1">@Html.Raw(slider.NombreSlider)</h1>
                </div>
            }
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#sliderImagenes" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#sliderImagenes" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

mvcProyectoWeb1/Views/Shared/_VistaCrearVolver.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear </button>
    </div>
    &nbsp;
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Volver atras</a>
    </div>
</div>